# This is a basic workflow to help you get started with Actions
name: CI-test-todo
# Controls when the action will run. Triggers the workflow on push events but only for the master branch
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install
      run: npm install
    - name: Run script file
      run: npm run todo
    - name: Auto commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated TODO
    - name: Build
      run: npm run build
      env:
        CI: true
    - name: Final Check
      if: ${{success()}}
      run: |
        echo Success
